version: 2
jobs:
  build:
    docker:
      - image: sicz/dockerspec
    environment:
      - MAKEFLAGS=--no-print-directory
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Download Docker images
          command: |
            make docker-pull docker-pull-dependencies
      - run:
          name: Build Docker image
          command: |
            make build
      - run:
          name: Test Docker image
          command: |
            make test
      - run:
          name: Security scan
          command: |
            make snyk
      - deploy:
          name: Push image to the Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
              make docker-push
            fi
